epochs: 1000
learning_rate: 0.001
batch_size: 64

sampling_steps: 64

# wingman required params
# https://github.com/jjshoots/Wingman?tab=readme-ov-file#from-wingman-import-wingman
model:
  save_directory: "weights"
  id: ""
  ckpt: 0
  increment_ckpt: false

logging:
  interval: 1
  max_skips: 5
  greater_than: 0.0
  filename: ""

wandb:
  enable: false
  save_code: false
  run:
    name: ""
    notes: ""
  project:
    name: "diffusion"
    entity: "jjshoots"
